Resolve #21 refactoring
Atema/trino pull request #2
Opened 2021-03-03 17:43 UTC by aoutir

2021-03-03 18:07 UTC, Atema requested changes

2021-03-03 18:07 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +        DataTypeTestToSqlDataTypeTestConverter.create()
If you use this, you need to read the output in the command line. Then use that (some changes may be required), to change DataTypeTest to SQLDataTypeTest.

2021-03-04 00:04 UTC, Atema commented
Take a look at #3. `TestPostgreSqlTypeMapping` in the repo can also be a good help.

2021-03-04 00:17 UTC, aoutir commented
Yes but they don't use the class `DataTypeTestToSqlDataTypeTestConverter`, I tried something I am trying to get the tests to run I will marked it ready to review if the tests are good

2021-03-04 00:33 UTC, Atema commented
If you run the code that's in your first commit, it should write the 
SqlDataTypeTest code to the standard output. That can be used as a basis 
for the rewritten tests.

------ Original Message ------
From: "aoutir" <notifications@github.com>
To: "Atema/trino" <trino@noreply.github.com>
Cc: "Martijn Atema" <martijn@atema.one>; "Review requested" 
<review_requested@noreply.github.com>
Sent: 04/03/2021 01:17:35
Subject: Re: [Atema/trino] Resolve #21 refactoring (#2)

>
>Yes but they don't use the class 
>DataTypeTestToSqlDataTypeTestConverter, I tried something I am trying 
>to get the tests to run I will marked it ready to review if the tests 
>are good
>
>—
>You are receiving this because your review was requested.
>Reply to this email directly, view it on GitHub 
><https://github.com/Atema/trino/pull/2#issuecomment-790179626>, or 
>unsubscribe 
><https://github.com/notifications/unsubscribe-auth/AAF5GNOT33AQ4TRIROOPSPDTB3GR7ANCNFSM4YRVMM6Q>.
>

2021-03-04 00:45 UTC, aoutir commented
SqlDataTypeTest code is also present in the message of the `RuntimeException `thrown in the method `execute `of the class `DataTypeTestToSqlDataTypeTestConverter ` that's why I am calling `getMessage ` to get the code and then I am executing it.
But I have just seen that the message starts with Code replacement so I can't use it directly

2021-03-04 00:46 UTC, Atema commented
The code will still need some changes that need to be edited manually

------ Original Message ------
From: "aoutir" <notifications@github.com>
To: "Atema/trino" <trino@noreply.github.com>
Cc: "Martijn Atema" <martijn@atema.one>; "Review requested" 
<review_requested@noreply.github.com>
Sent: 04/03/2021 01:45:24
Subject: Re: [Atema/trino] Resolve #21 refactoring (#2)

>
>SqlDataTypeTest code is also present in the message of the 
>RuntimeException thrown in the method execute of the class 
>DataTypeTestToSqlDataTypeTestConverter that's why I am calling 
>getMessage to get the code and then I am executing it.
>But I have just seen that the message starts with Code replacement so I 
>can't use it directly
>
>—
>You are receiving this because your review was requested.
>Reply to this email directly, view it on GitHub 
><https://github.com/Atema/trino/pull/2#issuecomment-790193727>, or 
>unsubscribe 
><https://github.com/notifications/unsubscribe-auth/AAF5GNMCEMNGE6VAIDGTQSLTB3J2JANCNFSM4YRVMM6Q>.
>

2021-03-04 00:56 UTC, aoutir commented
You're right, maybe I will see what I need to change clearly when I run the tests

2021-03-04 00:57 UTC, aoutir commented
if you still have the output can you post it here ?

2021-03-04 01:05 UTC, Atema commented
```
< FAILURE!
java.lang.RuntimeException:
Code replacement:
SqlDataTypeTest.create()
 .addRoundTrip("char(1) CHARACTER SET utf8", "'攻'", createCharType(1), "'攻'")
 .addRoundTrip("char(5) CHARACTER SET utf8", "'攻殻'", createCharType(5), "'攻殻'") // TODO non-identity toTrinoQueryResult function was used: 攻殻 vs 攻殻
 .addRoundTrip("char(5) CHARACTER SET utf8", "'攻殻機動隊'", createCharType(5), "'攻殻機動隊'")
 .execute( ... ) // TODO

        at io.trino.testing.datatype.DataTypeTestToSqlDataTypeTestConverter.execute(DataTypeTestToSqlDataTypeTestConverter.java:115)
        at io.trino.plugin.memsql.TestMemSqlTypeMapping.testMemSqlCreatedParameterizedCharUnicode(TestMemSqlTypeMapping.java:409)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

[ERROR] testTrinoCreatedParameterizedVarchar(io.trino.plugin.memsql.TestMemSqlTypeMapping)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.RuntimeException:
Code replacement:
SqlDataTypeTest.create()
 .addRoundTrip("varchar(10)", "'text_a'", createVarcharType(10), "'text_a'")
 .addRoundTrip("varchar(255)", "'text_b'", createVarcharType(255), "'text_b'")
 .addRoundTrip("varchar(256)", "'text_c'", createVarcharType(256), "'text_c'")
 .addRoundTrip("varchar(21844)", "'text_memsql_max'", createVarcharType(21844), "'text_memsql_max'")
 .addRoundTrip("varchar(21845)", "'text_memsql_larger_than_max'", createVarcharType(65535), "'text_memsql_larger_than_max'")
 .addRoundTrip("varchar(65535)", "'text_d'", createVarcharType(65535), "'text_d'")
 .addRoundTrip("varchar(65536)", "'text_e'", createVarcharType(16777215), "'text_e'")
 .addRoundTrip("varchar(16777215)", "'text_f'", createVarcharType(16777215), "'text_f'")
 .addRoundTrip("varchar(16777216)", "'text_g'", createUnboundedVarcharType(), "'text_g'")
 .addRoundTrip("varchar(2147483646)", "'text_h'", createUnboundedVarcharType(), "'text_h'")
 .addRoundTrip("varchar", "'unbounded'", createUnboundedVarcharType(), "'unbounded'")
 .execute( ... ) // TODO
```

2021-03-04 13:26 UTC, Atema requested changes

2021-03-04 13:26 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
>                  .execute(getQueryRunner(), trinoCreateAsSelect("trino_test_parameterized_varchar"));
Indentation should be 16.

2021-03-04 13:26 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +import java.io.*;
Remove this

2021-03-04 13:26 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +
Imports missing are createCharType and SqlDataTypeTest.

2021-03-04 13:26 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("char(1) CHARACTER SET utf8", "'攻'", createCharType(1), "'攻'")
You need to cast here as well (just like next line)

2021-03-04 13:26 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("char(5) CHARACTER SET utf8", "'攻殻機動隊'", createCharType(5), "'攻殻機動隊'")
Same

2021-03-04 13:26 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
>                  .execute(getQueryRunner(), trinoCreateAsSelect("trino_test_parameterized_varchar"));
You need to cast the right-hand side, like in the other function.

2021-03-04 13:26 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("char(5) CHARACTER SET utf8", "'攻殻機動隊'", createCharType(5), "'攻殻機動隊'")
`CHARACTER SET utf8` may not be nmecessary (not sure)

2021-03-04 23:27 UTC, aoutir commented
the tests are taking so long, they are working except for one I correct it I tried to run them again but they never end.
I guess it's working now it was just about a little detail but you never know run the tests again.

2021-03-05 08:36 UTC, Atema requested changes

2021-03-05 08:36 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("varchar", "'unbounded'", createUnboundedVarcharType(), "CAST('unbounded' AS varchar)")
You're almost done :). The type of the expected literal (4th argument) needs to be the same as the expected type (3rd argument). For example, in line 425 should have `CAST('text_h' AS varchar)`

2021-03-05 08:41 UTC, aoutir commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("varchar", "'unbounded'", createUnboundedVarcharType(), "CAST('unbounded' AS varchar)")
I need to change this only for line 424 and 425 right, the rest is good ?

2021-03-05 09:06 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("varchar", "'unbounded'", createUnboundedVarcharType(), "CAST('unbounded' AS varchar)")
422 as well

2021-03-05 13:45 UTC, aoutir commented
All the tests are working now

2021-03-05 14:19 UTC, Atema commented
Great!

2021-03-05 14:20 UTC, merged