Refactor for testJson and testDate
Atema/trino pull request #5
Opened 2021-03-04 11:52 UTC by linnea-bonnevier

Able to build it successfully but cannot run the tests

2021-03-04 12:37 UTC, linnea-bonnevier commented
Found some errors, will fix those and get back

2021-03-04 12:38 UTC, Atema requested changes
@linnea-bonnevier I was already working on some comments, so here they are.

2021-03-04 12:38 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +    private SqlDataTypeTest dateTestCases(DataType<LocalDate> dateDataType, ZoneId jvmZone, ZoneId someZone)
This function is run twice, with different `dataDataType`. Because `dataDataType` is not used, it does the same thing twice.

2021-03-04 12:38 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("date", "'DATE '''1983-10-01''", DATE, dateOfLocalTimeChangeBackwardAtMidnightInSomeZone.format(DateTimeFormatter.ofPattern("'DATE '''uuuu-MM-dd''")));
`''` and `'''` are there to deal with escaping for `DateTimeFormatter.ofPattern`. On the left hand side, `"DATE '1952-04-03'"` is enough.

2021-03-04 12:38 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +    private SqlDataTypeTest dateTestCases(DataType<LocalDate> dateDataType, ZoneId jvmZone, ZoneId someZone)
@caillouc Needs to do something similar for his PR.

2021-03-04 12:38 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("date", "'DATE '''1952-04-03''", DATE, LocalDate.of(1970, 1, 1).format(DateTimeFormatter.ofPattern("'DATE '''uuuu-MM-dd''"))) // before epoch
Left and right are not the same here.

2021-03-04 12:38 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("date", "'DATE '''1983-10-01''", DATE, dateOfLocalTimeChangeBackwardAtMidnightInSomeZone.format(DateTimeFormatter.ofPattern("'DATE '''uuuu-MM-dd''")));
Actually, because the type is set in the first argument, just `"'1952-04-03'"` is enough.

2021-03-05 14:24 UTC, linnea-bonnevier commented
@Atema I cannot figure out the json format tests, trying to figure out why extra " are added and how to get rid of them but without luck so far. This is the current output for that 

```
java.lang.AssertionError: [Rows] 
Expecting:
  <("{}", "null", "123.4", "\"abc\"", "\"\"", "{\"a\":1,\"b\":2}", "{\"a\":[1,2,3],\"b\":{\"aa\":11,\"bb\":[{\"a\":1,\"b\":2},{\"a\":0}]}}", "[]")>
to contain exactly in any order:
  <[({}, null, 123.4, "abc", "", {"a":1,"b":2}, {"a":[1,2,3],"b":{"aa":11,"bb":[{"a":1,"b":2},{"a":0}]}}, [])]>
elements not found:
  <({}, null, 123.4, "abc", "", {"a":1,"b":2}, {"a":[1,2,3],"b":{"aa":11,"bb":[{"a":1,"b":2},{"a":0}]}}, [])>
and elements not expected:
  <("{}", "null", "123.4", "\"abc\"", "\"\"", "{\"a\":1,\"b\":2}", "{\"a\":[1,2,3],\"b\":{\"aa\":11,\"bb\":[{\"a\":1,\"b\":2},{\"a\":0}]}}", "[]")>
```

2021-03-05 15:06 UTC, Atema commented
@linnea-bonnevier The problem is that you combined the two calls executes into one (they happen with different types). Therefore, they should be seperated into two, and each handled differently:

```
SqlDataTypeTest.create()
        ...
        .addRoundTrip("json", "123.4", JSON, "JSON '123.4'")
        .addRoundTrip("json", "'abc'", JSON, "JSON '\"abc\"'")
        ...
        .execute(getQueryRunner(), trinoCreateAsSelect("trino_test_json"));

        // MemSQL doesn't support CAST to JSON but accepts string literals as JSON values
SqlDataTypeTest.create()
        ...
        .addRoundTrip("json", "'123.4'", JSON, "JSON '123.4'")
        .addRoundTrip("json", "'\"abc\"'", JSON, "JSON '\"abc\"'")
        ...
        .execute(getQueryRunner(), memSqlCreateAndInsert("tpch.mysql_test_json"));
```

still needs some thinking for the complicated ones like `{}`, but for these it should work

2021-03-05 15:15 UTC, linnea-bonnevier commented
@Atema Nice, I've tried using the same types they are when creating the [jsonDataType](https://github.com/findepi/trino/blob/9087c42f0b23c05632ea8f18e75b57f913e400ae/presto-testing/src/main/java/io/prestosql/testing/datatype/DataType.java#L264) with the formatting but I can get it to work maybe I was just missing something

2021-03-05 15:33 UTC, Atema commented
Maybe this could be useful for the more advanced types: https://github.com/trinodb/docs.trino.io/blob/master/308/_sources/functions/json.rst.txt

2021-03-05 15:35 UTC, Atema commented
I think we can use `json_parse`

2021-03-05 17:08 UTC, linnea-bonnevier commented
I'll try and see what happens

2021-03-05 17:59 UTC, linnea-bonnevier commented
I cannot look at it more today I think I'm code blind, but the trino one still does not work. I'll continue to look into it tomorrow

2021-03-06 15:50 UTC, Atema requested changes

2021-03-06 15:50 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
>      }
I think these can just as well be combined as one functions with both statements to have them together again.

2021-03-06 15:50 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                // MemSQL doesn't support CAST to JSON but accepts string literals as JSON values
This one is at the wrong place; it should be before SqlDataTypeTest for the other one (the memSql one)

2021-03-06 15:51 UTC, Atema commented
I'll take a look at the date tests soon

2021-03-06 17:54 UTC, Atema requested changes

2021-03-06 17:54 UTC, Atema commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("date", "CAST('1983-10-01' AS date)", DATE, dateOfLocalTimeChangeBackwardAtMidnightInSomeZone.format(DateTimeFormatter.ofPattern("'DATE '''uuuu-MM-dd''")));
Needs some changes to work with all of the test cases. I think `dateTestCases` and `testDate` can be merged (because the same input and expected literals work for all cases. Maybe it can still be optimised a bit, but a working implementation would be as follows:

```java
    @Test
    public void testDate()
    {
        ZoneId jvmZone = ZoneId.systemDefault();
        checkState(jvmZone.getId().equals("America/Bahia_Banderas"), "This test assumes certain JVM time zone");

        ZoneId someZone = ZoneId.of("Europe/Vilnius");

        LocalDate dateOfLocalTimeChangeForwardAtMidnightInJvmZone = LocalDate.of(1970, 1, 1);
        verify(jvmZone.getRules().getValidOffsets(dateOfLocalTimeChangeForwardAtMidnightInJvmZone.atStartOfDay()).isEmpty());

        LocalDate dateOfLocalTimeChangeForwardAtMidnightInSomeZone = LocalDate.of(1983, 4, 1);
        verify(someZone.getRules().getValidOffsets(dateOfLocalTimeChangeForwardAtMidnightInSomeZone.atStartOfDay()).isEmpty());
        LocalDate dateOfLocalTimeChangeBackwardAtMidnightInSomeZone = LocalDate.of(1983, 10, 1);
        verify(someZone.getRules().getValidOffsets(dateOfLocalTimeChangeBackwardAtMidnightInSomeZone.atStartOfDay().minusMinutes(1)).size() == 2);

        for (String timeZoneId : ImmutableList.of(UTC_KEY.getId(), jvmZone.getId(), someZone.getId())) {
            Session session = Session.builder(getSession())
                    .setTimeZoneKey(TimeZoneKey.getTimeZoneKey(timeZoneId))
                    .build();

            SqlDataTypeTest.create()
                    .addRoundTrip("date", "CAST('1952-04-03' AS date)", DATE, "DATE '1952-04-03'") // before epoch
                    .addRoundTrip("date", "CAST('1970-01-01' AS date)", DATE, "DATE '1970-01-01'")
                    .addRoundTrip("date", "CAST('1970-02-03' AS date)", DATE, "DATE '1970-02-03'")
                    .addRoundTrip("date", "CAST('2017-07-01' AS date)", DATE, "DATE '2017-07-01'") // summer on northern hemisphere (possible DST)
                    .addRoundTrip("date", "CAST('2017-01-01' AS date)", DATE, "DATE '2017-01-01'") // winter on northern hemisphere (possible DST on southern hemisphere)
                    .addRoundTrip("date", "CAST('" + dateOfLocalTimeChangeForwardAtMidnightInJvmZone.toString() + "' AS date)",
                            DATE, "DATE '" + dateOfLocalTimeChangeForwardAtMidnightInJvmZone.toString() + "'")
                    .addRoundTrip("date", "CAST('" + dateOfLocalTimeChangeForwardAtMidnightInSomeZone.toString() + "' AS date)",
                            DATE, "DATE '" + dateOfLocalTimeChangeForwardAtMidnightInSomeZone.toString() + "'")
                    .addRoundTrip("date", "CAST('" + dateOfLocalTimeChangeBackwardAtMidnightInSomeZone.toString() + "' AS date)",
                            DATE, "DATE '" + dateOfLocalTimeChangeBackwardAtMidnightInSomeZone.toString() + "'")
                    .execute(getQueryRunner(), session, memSqlCreateAndInsert("tpch.test_date"))
                    .execute(getQueryRunner(), session, trinoCreateAsSelect(session, "test_date"))
                    .execute(getQueryRunner(), session, trinoCreateAsSelect(getSession(), "test_date"))
                    .execute(getQueryRunner(), session, trinoCreateAndInsert(session, "test_date"));;
        }
    }
```

2021-03-06 19:26 UTC, linnea-bonnevier commented on plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
> +                .addRoundTrip("date", "CAST('1983-10-01' AS date)", DATE, dateOfLocalTimeChangeBackwardAtMidnightInSomeZone.format(DateTimeFormatter.ofPattern("'DATE '''uuuu-MM-dd''")));
You are probably right, but that kind of falls outside our scope this time

2021-03-06 19:47 UTC, merged